name: Automerge

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - Run Tests

jobs:
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge Dependabot Pull Request
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
